### ISSUE TITLE
Don't works under Arena GUI

### ISSUE THREAD

**Issue by toni-chess** [pedro15/Snail-Chess#1]
Hi there!
Don't works under Arena GUI on any protocol UCI or Winbord.

**Comment by pedro15** [comment]
![imagen](https://github.com/user-attachments/assets/d4c95912-5915-481f-9bd6-9c3bab7ddb6d)

i managed to use it in arena with no problem. 
Make sure to follow the steps:
Engines > Install New Engine > Select "UCI" option > Select the executable file ( i recommend to install it on the own arena "Engines" folder )

if you see the engine taking too much to play a move, check the time controls in the Arena GUI, set to something lower.
If it did not worked, maybe it was that you didn't had .net installed, but with latest release ( https://github.com/pedro15/Snail-Chess/releases/tag/v1.0.1) you don't need to have .net installed anymore. 

Sorry for the delayed response
